### ISSUE TITLE
Install instructions do not work

### ISSUE THREAD

**Issue by SimonHeybrock** [ess-dmsc/generate-nexus-files#17]
`pip install -r requirements.txt` (as suggested in the README) does not work (cannot find `flatbuffers`). Also `nexusutils` is missing (trying to run `bigfake.py`). How can these things be installed?

**Comment by kmurica** [comment]
I just saw this issue. I bumped into this issue before a while ago and fixed it with the requirements-base.txt but did not update the README file. Could you test the new instructions I just pushed and confirm it works? Works on my side at least.
